apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: dotnet-instrumentation
  namespace: backend
spec:
  exporter:
    endpoint: http://signoz-otel-collector.monitoring.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
  dotnet:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:2.0.0
    env:
      - name: OTEL_SERVICE_NAME
        value: backend
      - name: OTEL_LOG_LEVEL
        value: debug