apiVersion: v1
kind: Service
metadata:
  name: signoz-mcp-server
  namespace: monitoring
spec:
  selector:
    app: signoz-mcp-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP